name: Release Changes

on: 
  push:
    branches:
      - main
      - notifyOnFail

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Throw a failure
      - name: Create failure
        run: exit 1

      # Handle failure and notify
      - name: Handle failure
        if: always()
        run: echo "Release failed! Issues encountered"