name: Release Changes

on: 
  push:
    branches:
      - main
      - notifyOnFail

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Throw a failure
      - name: Create failure
        run: exit 1

      # Handle failure and notify
      - name: Handle failure
        env:
          test_secret: ${{secrets.NOTIFICATION_WEBHOOK}}
        if: failure()
        run: |
          echo "Release failed! Issues encountered"
          if [ -z "$test_secret" ]; then
            echo "Could not find secret"
          else
            echo "Secret Found"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Open Source Pipeline Failure!/nAn issue occured in commit: ${{github.server_url}}/${{github.repository}}/commit/${{github.sha}}"}' $test_secret
          fi